language: python
python:
  - '3.5'
  - '3.6'
env:
  - BACKLOG_CONFIG=$TRAVIS_BUILD_DIR/travis/config.yaml

before_install:
  - pip install 'pytest==3.7.4'
  - pip install -U git+git://github.com/EBI-Metagenomics/emg-backlog-schema.git@develop
  - pip install -U git+git://github.com/EBI-Metagenomics/biome_prediction.git;
  - mysql -e 'CREATE DATABASE emg_backlog_2;'
  - emgbacklog migrate --database=default
  - mysql -u root --password="" --database=emg_backlog_2 < travis/biomes.sql

install:
  - $TRAVIS_BUILD_DIR/travis/create_ena_creds.sh

script:
  - python setup.py test

after_success:
  - pip install codacy-coverage
  - python-codacy-coverage -r coverage.xml