# coding: utf-8

"""
     

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.portal_api_api import PortalAPIApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPortalAPIApi(unittest.TestCase):
    """PortalAPIApi unit tests stubs"""

    def setUp(self):
        self.api = swagger_client.api.portal_api_api.PortalAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_using_get(self):
        """Test case for count_using_get

        Count rows matching search parameters  # noqa: E501
        """
        pass

    def test_do_sample_links_using_get(self):
        """Test case for do_sample_links_using_get

        Sample links  # noqa: E501
        """
        pass

    def test_do_study_links_using_get(self):
        """Test case for do_study_links_using_get

        Study links  # noqa: E501
        """
        pass

    def test_do_taxon_links_using_get(self):
        """Test case for do_taxon_links_using_get

        Taxonomy links  # noqa: E501
        """
        pass

    def test_download_doc_using_get(self):
        """Test case for download_doc_using_get

        Download the documentation as a PDF file.  # noqa: E501
        """
        pass

    def test_file_report_using_get(self):
        """Test case for file_report_using_get

        Get file report from warehouse search  # noqa: E501
        """
        pass

    def test_get_controlled_vocab_using_get(self):
        """Test case for get_controlled_vocab_using_get

        Get a list of available values for a controlled vocabulary field.  # noqa: E501
        """
        pass

    def test_get_results_using_get(self):
        """Test case for get_results_using_get

        Get a list of available result types (data sets) to search against.  # noqa: E501
        """
        pass

    def test_get_return_fields_using_get(self):
        """Test case for get_return_fields_using_get

        Get a list of fields that can be returned for a result type.  # noqa: E501
        """
        pass

    def test_get_search_fields_using_get(self):
        """Test case for get_search_fields_using_get

        Get a list of searchable fields for a result type.  # noqa: E501
        """
        pass

    def test_search_post_using_post(self):
        """Test case for search_post_using_post

        Perform a warehouse search with POST  # noqa: E501
        """
        pass

    def test_search_using_get(self):
        """Test case for search_using_get

        Perform a warehouse search  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
